<?php

return [
    'show_warnings' => false,
    'public_path' => null,
    'convert_entities' => true,
    'options' => [
        'font_dir' => storage_path('fonts'),
        'font_cache' => storage_path('fonts'),
        'temp_dir' => sys_get_temp_dir(),
        'chroot' => realpath(base_path()),
        'allowed_protocols' => [
            "file://" => ["rules" => []],
            "http://" => ["rules" => []],
            "https://" => ["rules" => []],
        ],
        'log_output_file' => null,
        'enable_font_subsetting' => true,
        'is_remote_enabled' => true,
        'dpi' => 96,
        'enable_php' => false,
        'enable_javascript' => true,
        'enable_remote' => true,
        'font_height_ratio' => 1.1,
        'is_html5_parser_enabled' => true,
    ],
    'default_paper_size' => 'a4',
    'default_font' => 'Arial',
    'default_media_type' => 'screen',
    'default_orientation' => 'portrait',
    'dpi' => 96,
    'font_dir' => storage_path('fonts'),
    'font_cache' => storage_path('fonts'),
    'temp_dir' => sys_get_temp_dir(),
    'chroot' => realpath(base_path()),
    'allowed_protocols' => [
        "file://" => ["rules" => []],
        "http://" => ["rules" => []],
        "https://" => ["rules" => []],
    ],
    'log_output_file' => null,
    'enable_font_subsetting' => true,
    'is_remote_enabled' => true,
    'is_html5_parser_enabled' => true,
];
